[package]
name = "pipitdb-operators"
description = "The tables, sources and operators pipitdb comes with."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "pipit_operators"

[dependencies]
pipitdb-kernel = { path = "../kernel" }

[lints]
workspace = true
