[package]
name = "pipitdb-size"
description = "A Wasm module that uses the kernel, for measuring binary size."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
pipitdb-kernel = { path = "../kernel" }

[lints]
workspace = true
