[package]
name = "pipitdb-bench"
description = "Benchmarks for pipitdb."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
pipitdb-kernel = { path = "../kernel" }

[dev-dependencies]
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }
gungraun = "0.20"

[[bench]]
name = "wall_clock"
harness = false

[[bench]]
name = "instructions"
harness = false

[lints]
workspace = true
