[package]
name = "pipitdb-std"
description = "pipitdb's standard stages."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "pipit_std"

[dependencies]
pipitdb-kernel = { path = "../kernel" }

[lints]
workspace = true
